In [ ]:
import numpy as np
a=100,2,87,9,9,6,4
np.array(a)
type(a)
np.ndim(a)



1

In [ ]:
c=np.array([[4,5,6],[1,2,3]])
np.ndim(c)


2

In [ ]:
aa=10
import numpy as np
array=np.array(aa)
type(array)
np.ndim(aa)


0

In [ ]:
dd=np.array([[1,2,3],[4,5,6]])
np.ndim(dd)


2

In [ ]:
tt=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
np.ndim(tt)

3

In [ ]:
a=np.array([[1,2,3,4],[1,23,4,6]])
a.size

8

In [ ]:
a.shape

(2, 4)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
n=np.arange(1,100,2)
n

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
n=n.astype("float")
n

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [ ]:
s=np.array([[[ 1,  2,  3],[ 4,  5,  6]],[[ 1,  2,  3],[ 9, 10, 11]]])
s

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 1,  2,  3],
        [ 9, 10, 11]]])

In [ ]:
np.ndim(s)

3

In [ ]:
#array properties
#ndim
#shape
#size
#dtype


In [ ]:
s.shape

(2, 2, 3)

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.size

12

In [ ]:
np.linspace(1,100,20)


array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [ ]:
mat=np.arange(1,37)
mat


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [ ]:
mat=mat.reshape(6,6)
mat

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
mat[1:4,2:5]

array([[ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23]])

In [ ]:
def fun(l):
    return l*5
l=[1,2,3,4,5]
m=list(map(fun,l))
m

[5, 10, 15, 20, 25]

In [ ]:
la=np.array(l)
print(la*5)

[ 5 10 15 20 25]


In [ ]:
a=[1,2,3]
print(a)
b=[[4],[5],[6]]
print(b)
c=a+b

[1, 2, 3]
[[4], [5], [6]]


In [ ]:
np.ndim(a)

1

In [ ]:
np.ndim(b)

2

In [ ]:
np.sum(b)

np.int64(15)

In [ ]:
np.max(b)

np.int64(6)

In [ ]:
np.min(b)

np.int64(4)

In [ ]:
np.mean(a)

np.float64(2.0)

In [ ]:
np.median(a)

np.float64(2.0)

In [ ]:
np.log(b)

array([[1.38629436],
       [1.60943791],
       [1.79175947]])

In [ ]:
np.sqrt(b)

array([[2.        ],
       [2.23606798],
       [2.44948974]])

In [ ]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.std(a)

np.float64(0.816496580927726)

In [ ]:
np.dot(a,b)

array([32])

In [ ]:
np.dot(a,b)

array([32])

In [ ]:
np.random.rand(4,4)

array([[0.16137228, 0.36702793, 0.5723631 , 0.95987137],
       [0.88428592, 0.14833563, 0.17740049, 0.09302096],
       [0.19435868, 0.88761067, 0.10086196, 0.512168  ],
       [0.08367867, 0.67844604, 0.19438007, 0.62171181]])

In [ ]:
np.random.randint(1,1000,6)

array([685, 249, 186, 541,  80, 231])

In [ ]:
np.random.normal(8,2,100)#mean.std.size

array([ 8.3191895 ,  7.12709295,  6.34937072,  5.90323322,  7.14529853,
        7.93345369,  7.58424083, 10.89632746,  5.74900173,  7.02318742,
        6.74941228,  5.75707799,  7.38012062,  8.05097208,  7.54585112,
        7.55007398,  5.99147674, 11.37522323,  8.54216261,  7.93708638,
       10.30120134,  6.60670797,  7.5557648 , 10.99036824,  7.50629912,
        8.52885985,  7.82970974,  8.47095487,  8.26986071,  8.41275548,
        9.62806489,  4.49782222,  7.60652345, 13.09490793,  8.49447756,
        8.41205026,  5.1922184 ,  6.21593151, 10.292013  ,  6.7478911 ,
        7.83033301,  5.03103652,  8.7089531 ,  8.66614538,  4.85238957,
        9.78149353,  8.81313311,  8.21148236,  9.06416072,  7.49439006,
        3.25299817, 10.47503249,  9.44653084,  8.92098196, 10.87341897,
       10.42671366,  9.29464433,  3.55361676,  7.55235597,  9.95121258,
       11.01574828,  6.87071894,  8.35300474,  4.85554311,  6.63515096,
        8.12347002, 12.72105308,  5.60283165,  8.11598095,  9.09

In [ ]:
ans=np.array([7.51725992,  8.50552092,  9.39225711,  9.24925719,  7.09228087,
        7.71674333,  5.75056828,  9.70361516,  7.8544011 ,  7.59788879,
        5.98582347,  4.88451458,  9.21809831,  6.81789518,  5.62955695,
        9.7408562 ,  6.40121169,  7.08716935,  9.38052392,  6.20724987,
        7.53877622, 10.1837204 ,  9.63670821,  9.38642754,  7.07700196,
        8.30282379, 10.33468406,  7.64113665,  6.09672472, 10.50451693,
       11.59716018,  7.88687434,  7.24282714,  2.76303383,  5.78174284,
        7.54498548,  7.33379038,  8.13295055,  9.27443983,  6.72101968,
        9.30175664,  8.27468071, 10.15386949,  7.18772669,  6.73398007,
        4.24018789,  6.45091909,  4.5789646 , 10.79695388,  6.83678163,
        7.44629291,  5.0526935 ,  7.65568003,  6.17519687, 10.2516464 ,
       10.14571177, 10.02379497,  8.90167115,  9.92944174,  0.74771317,
        8.79636197,  8.18017465,  6.33078356,  8.4865959 , 11.41699828,
        7.08785265,  7.15496299,  8.52605463,  7.64757089, 10.31352312,
       10.49656193,  9.79332802,  8.86268617,  6.35265309,  6.57916653,
        9.21002471,  9.01095405,  9.15108676,  5.20231834,  5.97090761,
        6.50331015,  7.58924371,  8.7199747 ,  6.08733522,  4.71322635,
       11.75444485,  7.80491944,  9.11063539,  7.48472097,  7.81127641,
        6.51272826,  8.81872719,  6.81875994,  8.55401717,  8.20283605,
        9.14980737,  6.82701979,  8.33115192,  5.77380775,  7.18110958])

In [ ]:
np.mean(ans)

np.float64(7.8191931818)

In [ ]:
np.float64(7.8191931818)

np.float64(7.8191931818)

In [ ]:
np.std(ans)

np.float64(1.8661855080144982)

In [ ]:
c

[1, 2, 3, [4], [5], [6]]

In [ ]:
c=np.array([[5,6,7],[6,7,8],[7,8,9]])

In [ ]:
c>7


array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [ ]:
print(c.reshape(-1,1))
print(c.reshape(1,-1))

[[5]
 [6]
 [7]
 [6]
 [7]
 [8]
 [7]
 [8]
 [9]]
[[5 6 7 6 7 8 7 8 9]]


In [ ]:
c.flatten()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [ ]:
c.ravel()

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [ ]:
np.vstack(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
np.hstack(c)

array([5, 6, 7, 6, 7, 8, 7, 8, 9])

In [ ]:
np.sort(c)

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
np.hsplit(c,3)

[array([[5],
        [6],
        [7]]),
 array([[6],
        [7],
        [8]]),
 array([[7],
        [8],
        [9]])]

In [ ]:
np.vsplit(c,3)

[array([[5, 6, 7]]), array([[6, 7, 8]]), array([[7, 8, 9]])]

In [ ]:
np.sum(c,axis=0)

array([18, 21, 24])

In [ ]:
c

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])